"""empty message

Revision ID: 47cb65814c34
Revises: 900bfab117f1
Create Date: 2024-03-30 00:46:55.603099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47cb65814c34'
down_revision = '900bfab117f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_planet_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_unique_constraint('characters_planet_id_key', ['planet_id'])

    # ### end Alembic commands ###
